### PR TITLE
Fixed: Coin info API doesn't properly implement HTTP protocol (Fixes #44)

### LINKED ISSUE #44: HTTP Client does not expose require error granularity
The HTTP client we currently use provides its clients contextless errors. For instance it does not expose the underlying HTTP response status code. For this reason it is not possible to determine if the request failed for a temporary HTTP5xx reason or for a permanent one e.g. Not Found, or too many requests.

### PR DESCRIPTION
**Pull request by arein**
Coininfo API doesn't implement HTTP Not Found and fails such requests with HTTP Internal Server Error instead.

The HTTP client used does not expose said errors.

Changes:
* Coininfo API now returns HTTP 404 when coin is not available
* Coininfo API does some more input validation and returns HTTP 400 when validations fail 
* Uses `resty` as HTTP client
* Removes HTTP level caching - potentially problematic but  #47 introduces app layer caching
* Introduces functional test for Coininfo API

Also adding the Codecov token to `.codecov.yml`. This should not be required when using Azure Pipelines and public repositories but it sometimes works and sometimes fails. Improvement would be to move the token to the Azure environment. I see no security concern with adding this here.

#### Testing
Ran `newman` tests and `make test`

### CODE REVIEW

File: api/marketdata.go [hunk 1]
```diff
@@ -173,26 +173,39 @@ func getChartsHandler() func(c *gin.Context) {
...
 
 		token := c.Query("token")
 		currency := c.DefaultQuery("currency", watchmarket.DefaultCurrency)
 		chart, err := charts.GetCoinInfo(uint(coinId), token, currency)
-		if err != nil {
-			logger.Error(err, "Failed to retrieve coin info", logger.Params{"coin": coinId, "currency": currency})
+		if err == watchmarket.ErrNotFound {
+			ginutils.RenderError(c, http.StatusNotFound, fmt.Sprintf("Coin info for coin id %d (token: %s, currency: %s) not found", coinId, token, currency))
+			return
+		} else if err != nil {
```
Comment (EnoRage) [inline api/marketdata.go]: if err != nil 
there is no sense to have it here

Comment (arein) [reply api/marketdata.go]: I don't understand?
Are you saying the `else` is redundant?
